### ISSUE TITLE
Problema encontrado referente a Cors

### ISSUE THREAD

**Issue by andremartinsds** [lrpatricio/b2c-challenge#16]
Fui testar a api e notei que está com um pequeno problema de cors.

Acredito que a solução seria alterar no arquivo: https://github.com/lrpatricio/b2c-challenge/blob/develop/api/src/core/helpers/Json.php

de
```
return $response
            ->withHeader('Content-Type', 'application/json')
            ->withStatus($status);
```
para
```
 return $response
            ->withHeader('Access-Control-Allow-Origin', '*')
            ->withHeader('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type, Accept, Origin, Authorization')
            ->withHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS')
            ->withHeader('Content-Type', 'application/json')
            ->withStatus($status);
```
obs. não tenho certeza se essa forma seria a mais segura, se quiser posso subir o pull request.

**Comment by marcosvto1** [comment]
"->withHeader('Access-Control-Allow-Origin', '*')"  para ambiente de teste esta ok em colocar, mais acho deveria colocar em um middleware

**Comment by andremartinsds** [comment]
Marcos adicionou os headers no arquivo de rotas, problema resolvido.
https://github.com/lrpatricio/b2c-challenge/blob/develop/api/src/routes.php
